# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

test_dissimilarities_class <- function(v, y, w, alpha) {
    .Call(`_ProbKMAcpp_test_dissimilarities_class`, v, y, w, alpha)
}

