// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif


RcppExport SEXP _rcpp_module_boot_H1Module();
RcppExport SEXP _rcpp_module_boot_L2Module();
RcppExport SEXP _rcpp_module_boot_MotifH1Module();
RcppExport SEXP _rcpp_module_boot_MotifL2Module();
RcppExport SEXP _rcpp_module_boot_ProbKMAModule();

static const R_CallMethodDef CallEntries[] = {
    {"_rcpp_module_boot_H1Module", (DL_FUNC) &_rcpp_module_boot_H1Module, 0},
    {"_rcpp_module_boot_L2Module", (DL_FUNC) &_rcpp_module_boot_L2Module, 0},
    {"_rcpp_module_boot_MotifH1Module", (DL_FUNC) &_rcpp_module_boot_MotifH1Module, 0},
    {"_rcpp_module_boot_MotifL2Module", (DL_FUNC) &_rcpp_module_boot_MotifL2Module, 0},
    {"_rcpp_module_boot_ProbKMAModule", (DL_FUNC) &_rcpp_module_boot_ProbKMAModule, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_ProbKMAcpp(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
