// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// test_dissimilarities_class
double test_dissimilarities_class(const List& v, const List& y, const arma::vec& w, double alpha);
RcppExport SEXP _ProbKMAcpp_test_dissimilarities_class(SEXP vSEXP, SEXP ySEXP, SEXP wSEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const List& >::type v(vSEXP);
    Rcpp::traits::input_parameter< const List& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type w(wSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(test_dissimilarities_class(v, y, w, alpha));
    return rcpp_result_gen;
END_RCPP
}

RcppExport SEXP _rcpp_module_boot_ParametersModule();

static const R_CallMethodDef CallEntries[] = {
    {"_ProbKMAcpp_test_dissimilarities_class", (DL_FUNC) &_ProbKMAcpp_test_dissimilarities_class, 4},
    {"_rcpp_module_boot_ParametersModule", (DL_FUNC) &_rcpp_module_boot_ParametersModule, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_ProbKMAcpp(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
